config/routes.rb
HtmlScraper::Application.routes.draw do
  
  root :to => "pages#home"   
 
  match 'scrapes/new' => 'scrapes#new'
  match'/scrapes' => 'scrapes#index'
  
  resources :scrapes

end

app/models/scrape.rb
require 'open-uri'

class Scrape < ActiveRecord::Base      
  
  attr_accessor :title
  
  validates_uniqueness_of :image 
  
  
  url = "http://www.electronicaoasis.com"
  doc = Nokogiri::HTML(open(url))



  doc.css(".hentry").each do |entry|
    title = entry.at_css("h2 a").text unless title
      if entry.at_css(".size-full") != nil
        image = entry.at_css(".size-full")[:src]
      else
        image = "there is no image"
      end 
    post_date = entry.at_css(".postdate").text
    url = entry.at_css("h2 a")[:href] unless url 

      # article_info = Nokogiri::HTML(open(url)) 

      # para_info = (article_info/"p").text
    
    @scrape = Scrape.new(
      :title => title,
      :url => url,
      :image => image,
      :post_date => post_date )
      # :para_info => para_info)                

    unless @scrape.title = nil
      @scrape.save 
    end  
  end   
  
  # raise puts @scrape.inspect        
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
     @scraped = Scrape.all
  end

end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController 
  
  
  def index
    @scrapes = Scrape.all
  end
  
  def new
    @scrapes = Scrape.all 
    @scrape = Scrape.new(
      :title => @title,
      :url => @url,
      :image => @image,
      :post_date => @post_date )
      
    @scrape.save
  end 
  
  def update
    @scrape = Scrape.new(
      :title => @title,
      :url => @url,
      :image => @image,
      :post_date => @post_date )
      
    @scrape.save
  end
  
  def destroy
    @scrape = Scrape.find(params[:id])   
    @scrape.destroy
    
    respond_to do |format|
       format.html { redirect_to(scrapes_path) }
       format.xml  { head :ok }
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HtmlScraper</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>  

<table>
	      <tr>
					<td>Title:</td>
					<td>ID:</td>
					<td>URL:</td>
					<td>Image:</td>
					<td>Post Date:</td>
				</tr>
	
			 <% @scraped.each do |s| %>
				<tr>
			 	  <td><%= s.title  %></td>
		 			<td><%= s.id %></td>
					<td><%= s.url %></td>
					<td><%= s.image %></td> 
					<td><%= s.post_date %></td>
				 </tr> 
			 <% end %>
</table> 
               
<%= @scraped.count %> 
<%= @scraped[0].inspect %>
  

app/views/scrapes/index.html.erb
<table>
	      <tr>
          <td>ID:</td>
					<td>Title:</td>
					<td>URL:</td>
					<td>Image:</td>
					<td>Post Date:</td>
				</tr>
	
			 <% @scrapes.each do |scrape| %>
				<tr>
					<td><%= scrape[:id] %></td> 
			 	  <td><%= scrape[:title] %></td>
					<td><%= scrape[:url] %></td>
					<td><%= scrape[:image] %></td> 
					<td><%= scrape[:post_date] %></td> 
					<td><%= link_to "Delete", scrape, :confirm => 'Are you sure?', :method => :delete %></td> 
				 </tr> 
			 <% end %>
</table>               


<%= link_to "New Scrape", scrapes_new_path %>

app/views/scrapes/new.html.erb
<table>
	      <tr>
          <td>ID:</td>
					<td>Title:</td>
					<td>URL:</td>
					<td>Image:</td>
					<td>Post Date:</td>
				</tr>
	
			 <% @scrapes.each do |s| %>
				<tr>
					<td><%= s[:id] %></td> 
			 	  <td><%= s[:title] %></td>
					<td><%= s[:url] %></td>
					<td><%= s[:image] %></td> 
					<td><%= s[:post_date] %></td>
				 </tr> 
			 <% end %>
</table>



<%= form_for(@scrape) do |f| %>                 
	<%= f.submit %>
<% end %>